//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Category
    {
        public int MaGame { get; set; }
        public string TenGame { get; set; }
        public string AnhBia { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string TenHangMuc { get; set; }
    }
}
