//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPost
    {
        public int PostID { get; set; }
        public string PostName { get; set; }
        public string PostImg { get; set; }
        public string PostDesc { get; set; }
        public Nullable<System.DateTime> dayUpdated { get; set; }
        public string PostNameFull { get; set; }
    }
}
